### PR TITLE
Added LOFAR magnetic field values to sites

### PR DESCRIPTION
**Pull request by MijnheerD**

### CODE REVIEW

**Review by fschlueter — APPROVED** [review]
Hi,
the typical rule is that you can merge this change yourself once it is approved.

**Comment by MijnheerD** [comment]
@fschlueter I would love to, but I don't have write access to the repo :(

**Comment by anelles** [comment]
Nothing that admin rights cannot fix. 
FYI, in particular @cg-laser: Mitja works on LOFAR and wants to use radiotools for a revised version of the LOFAR reconstruction, which I highly encourage.

**Comment by cg-laser** [comment]
Hej Mitja, thanks for contributing. PR looks good. I just wanted to send you an invitation but it seems that Felix already did this ;-) Just accept the invitation and then you can merge the pull request. Thanks

**Pull request merged**
