### PR TITLE
Add function for average density

### PR DESCRIPTION
**Pull request by fschlueter**
Hi,
as the commit massages say...
Cheers

### CODE REVIEW

**Comment by fschlueter** [comment]
Okay, it does not work as intended, I am on...

**Comment by fschlueter** [comment]
Now it works for me.

**Comment by fschlueter** [comment]
hey @cg-laser  what do you think?

**Comment by cg-laser** [comment]
better use built in function caching: https://docs.python.org/3/library/functools.html lru_cache

**Comment by fschlueter** [comment]
yep, that is much better!

**Review by cg-laser — APPROVED** [review]

**Pull request merged**
