### PR TITLE
Extend refractivity

### PR DESCRIPTION
**Pull request by fschlueter**
Hi @cg-laser, 
as you can see here are included some changes which are quite old. Also the commit history is somehow polluted with identical commits? How could I fix this (make a clean branch and cherry-pick?).

As far as I oversee the changes they mainly include the support of GDAS files for both classes. I think we want that! Do you have any comments?

Cheers

### CODE REVIEW

**Comment by fschlueter** [comment]
And yes I would still need to add some docstrings :)

**Review by cg-laser — CHANGES_REQUESTED** [review]
I think this is a useful additon. Thanks for implementing it. 

Could you add a general explanation how to use the GDAS files, and how they are processed. And a few more doc strings would be great. 

You introduce a new `n_0`. Will this change prior results?

**Comment by fschlueter** [comment]
Hi, will do so. No, I introduced n_0 to be able to calculated the integrated refractive index along an axis. I use the same value as in the "static" function get_n.

**Comment by fschlueter** [comment]
@cg-laser, quite some time I worked on this. The py3 tests pass. Can we merge it?

**Comment by fschlueter** [comment]
Can this be merged?

**Review by cg-laser — APPROVED** [review]

**Pull request merged**
