### PR TITLE
add helper for 2d histogram with column norm

### PR DESCRIPTION
**Pull request by cg-laser**

### CODE REVIEW

**Comment by fschlueter** [comment]
Hi, I am on holidays until Monday. In general i am in strong favor of pcolor() instead of imshow(). It gives you more control of binned data.
Cheers

**Comment by cg-laser** [comment]
feel free to improve the method. I'm not really an expert on these functions

**Comment by fschlueter** [comment]
Hi,
In my opinion that is a bit 'safer and pcolormesh has even for functionality.
Is there a reason why this function does not hat a similar interface as get_histogram()?
In principle  i would like to extend this function to be a normal 2d histogram ploter with with option to normalize. however that costs some time. So i am good to go with that.

**Review by fschlueter — APPROVED** [review]

**Comment by fschlueter** [comment]
can we finish that?

**Pull request merged**
