### PR TITLE
changed threshold when to use numerical integrations since with the c…

### PR DESCRIPTION
**Pull request by fschlueter**
…urrent value the comparision between taylor and numeric failes.

### CODE REVIEW

**Comment by fschlueter** [comment]
I have rebased this branch with the master, and then merged local and remote branch together (probably not the best solution).
The CI tests should be successful here!

**Comment by fschlueter** [comment]
Hey @cg-laser any objectives to change that?
However I would rather push a new commit to the master. I think when we merge this branch we pollute our git log
Felix

**Comment by cg-laser** [comment]
aren't here many changed that have been merged already? If possible, its probably better to make a new pull request only with the new changes. You only want to change the zenith angle threhold right/

**Comment by fschlueter** [comment]
yep this pr is polluted, this is why I wanted to propose, once we decided here, we just push a single commit to the master branch changing the zenith threshold.

**Comment by fschlueter** [comment]
created new, clean pr.

**Pull request closed without merging**
