### PR TITLE
CoREAS file selector

### PR DESCRIPTION
**Pull request by christophwelling**
I wrote a script that selects CoREAS files from a given list of folders so that they follow a desired direction and energy distribution. Thought this might be useful for others as well.

### CODE REVIEW

**Comment by fschlueter** [comment]
Hi,
I think we should not have any NuRadioReco dependency in this library.

**Comment by christophwelling** [comment]
Oops, forgot about that. I'm going to remove the dependencies

**Comment by fschlueter** [comment]
Great, Thanks! I would have two remarks:
1. Do we want to open the box of Pandora when speaking about coding style? :) 
2. Why storing the event list as pickle? There is no need or? and a human readable from would be more handy I think.
Cheers

**Comment by christophwelling** [comment]
1. What's wring with the coding style?
2. Why not? It's just about speeding things up. If you have a lot of files, it can take a while to loop over them, so I only want to do that once and then use the pickle, which is much faster. You may want to re-run that a couple times in case the results look weird. I don't see why you would need it human-readable.

**Comment by fschlueter** [comment]
Hi,

To 2.: Ah okay I did not expect it to be an time issue. If so I guess pickle is fine.
To 1.: Ah I know I am always quite anal... Sometime more spaces or empty lines could improve reading:)

**Comment by cg-laser** [comment]
@fschlueter @christophwelling is this PR good to go? It seems to be idle since a long time.

**Comment by christophwelling** [comment]
As far as I'm concerned, this can be merged

**Review by cg-laser — APPROVED** [review]

**Pull request merged**
