### PR TITLE
Imports xrange from past to make code work for py3

### PR DESCRIPTION
**Pull request by christophwelling**

### CODE REVIEW

**Review by anelles — APPROVED** [review]
Looks good and fix is needed.

**Comment by cg-laser** [comment]
I think it is better to just replace `xrange` with `range`. In p3 `range` is clever enough to return an interator when looping over it.

**Comment by fschlueter** [comment]
right but this is not true for the range in p2 right? So it might slow done p2?

**Comment by cg-laser** [comment]
yes in principle, but I think this is negligible. And we anyway want to focus on p3, so a little less performance in p2 is ok I'd say. And then we don't need the extra import.

**Pull request merged**
