### PR TITLE
Fix bug in the numerical calculation of atmosphere between to points.

### PR DESCRIPTION
**Pull request by fschlueter**
When the atmosphere is calculated numerically as function of the zenith angle and distance, the observation level has to be taken into account since the height above ground h=h(theta, d, obs_lvl) depends on it. For other calculations this seems not necessary.

### CODE REVIEW

**Comment by fschlueter** [comment]
hey @cg-laser, do you have any subjection? I realized that when calculating the atm between 2 positions in the atmosphere with that function and a own numerical calculation (using a Riemann-Summe).

**Comment by cg-laser** [comment]
Doesn't your change, change the definition of `h_low`? If `h_low` is the height with respect to sea level the function is already correct, isn't it?

**Comment by cg-laser** [comment]
It seems that you change is correct if `h_low` is interpreted as the height above the observation level. But I'm not sure if we want to change that. It probably does not beak anything because the default value is still obs=0. 
In any case, we should document it properly (which I never did so far :-( )

**Comment by fschlueter** [comment]
No, h_low should still be interpreted as height above sea level not ground. That is why the observation level is subtracted from `t_h_low` when calculating the distance for height above ground. However the relation d(zenith, height) changes for different observation levels.

**Comment by fschlueter** [comment]
grafik

**Comment by cg-laser** [comment]
with this screenshot, do you want to show that the two calculations agree? (which I think they should)

**Comment by fschlueter** [comment]
Well they do not agree, right?

**Comment by cg-laser** [comment]
the difference is tiny. This might also be numerical precision. 
But we would expect that they agree, don't we? I don't see how the result can be any different (except for numerical problems)

**Comment by fschlueter** [comment]
I am a bit confused, sorry. These are analytical function, right? And as I said d(h, zenith, obs_lev1) !=  d(h, zenith, obs_lev2) and thus delta_d(delta_h, zenith, obs_lev1) != delta_d(delta_h, zenith, obs_lev2), right?

**Comment by cg-laser** [comment]
your height is always above the observation level. So when you decrease your observation level, you increase the distance in the same way, i.e. going from  d(3000, zenith, 1000) to d(3000, zenith, 0) will increase the distance by the same amount as going from d(2000, zenith, 1000) to d(2000, zenith, 0). You just add the additional path from 0 m asl to 1000m asl

**Comment by fschlueter** [comment]
Hm I still confused. I can not really argue with the above but when I do the calculation with the function in models.py (`get_distance_for_height_above_ground`) i get a (sizeable) difference. And when I did the calculation of the atmosphere between two points numerically (`get_atmosphere`) I got differences to the models.py method once I changed the observation height. I think what might be the issue here is the definition of the zenith angle. I assumed the zenith angle is defined at the observation level. However a line between two points will have a different zenith angle at a observation level != 0 than on sea level. Thus when using this zenith angle (defined by the zenith at obs_lev) to calculated the atmosphere of two points given their heights, the distances have to be calculated using this obs_lev.

**Comment by fschlueter** [comment]
This is a minimal example of what I meant. I am a bit confused now why I do not get the same results at 80 deg for the my numerical method and any of the methods in models.py. Maybe you can spot my the issue. Sorry the code quoting is not correct. 

`import numpy as np
from radiotools.atmosphere import models as atm
from radiotools import helper`

`def get_grammage_between_two_points_numerical(p1, p2, atm_model, debug=False):
    """
    Numerical calculation of the integrated refractivity between two positions along a straight line in the atmosphere.
    Takes curvature of a spherical earth into account.
    p1 and p2 need to be in the same coordiate system with the origin at sea level.

    Parameters
    ------------
    p1 : array (3,)
        coordinates in meter.
    p2 : array (3,)
        coordinates in meter.
    atm_model : int
        Number of the atmospheric model (from radiotools.atmosphere.models) which provides the desity profile rho(h)
        to calculate the refractivity via N(h) = N(0) * rho(h) / rho(0).
    debug : bool
        If True, prints out debug output (default: False).


    Returns
    --------
    integrated refractivity : float
    """
    line = p1 - p2
    max_dist = np.linalg.norm(line)
    zenith = helper.get_local_zenith_angle(p1, p2)

    # nsteps = max(1000, min(int(max_dist / 100), 2001))
    nsteps = int(max_dist / 10)
    distances = np.linspace(0, max_dist, nsteps, endpoint=False)
    obs_level = helper.get_local_altitude(p2)

    dstep = distances[1] - distances[0]
    grammage = 0
    for dist in distances:
        height_asl = atm.get_height_above_ground(dist + dstep / 2, zenith, observation_level=obs_level) + obs_level
        rho = atm.get_density(height_asl, model=atm_model)
        grammage += rho * dstep

    if debug:
        height_max = atm.get_height_above_ground(max_dist, zenith, observation_level=obs_level) + obs_level
        print("calculate num for %.3f deg, %.1f m distance, %.1f m min height, %.1f m max height" % (np.rad2deg(zenith), max_dist, obs_level, height_max))

    return grammage / 100 ** 2  # g/m2 to g/cm2`

`at = atm.Atmosphere(27, zenith_numeric=0)
for zenith in np.deg2rad(np.arange(80, 89, 1)):
    p0 = np.array([0, 0, 0])
    p1 = helper.spherical_to_cartesian(zenith, 0) * 2e5

    for obs_level in [0, 1400, 3000]:
        # local coordinate system
        core = np.array([0, 0, obs_level])

        # numerical calculations
        X_num = get_grammage_between_two_points_numerical(p1 + core, p0 + core, 27, debug=False)
        
        # height above sea level of p1 (for p0 its obs_level)
        h_p1 = atm.get_height_above_ground(2e5, zenith, obs_level) + obs_level
        
        # calculation as before, with absolut heights and without obs_level
        X_at = at.get_atmosphere(zenith, obs_level, h_p1)

        # calclation now with obs_level
        X_at_corr = at.get_atmosphere(zenith, obs_level, h_p1, obs_level)
        
        # calculation as before but with corrected zenith angle
        zenith_at_earth, distance_to_earth = helper.get_zenith_angle_at_earth(zenith, obs_level)
        X_at_test = at.get_atmosphere(zenith_at_earth, obs_level, h_p1)


                
        print(r"{:.0f}, {:04d}m: {:.4f}, {:.4f}, {:.4f}".format(np.rad2deg(zenith), obs_level, X_at / X_num, X_at_corr / X_num, X_at_test / X_num))
`

**Comment by cg-laser** [comment]
I'm still a bit confused, but you are probably right that the zenith angle changes at different observation heights because it is always relative to the ground plane which rotates because of Earth curvature. 
In you checks, do you see that the difference is small (or zero) for small zenith angles and then increases with higher zenith angles?

**Comment by fschlueter** [comment]
Hi, yes indeed the difference is small for vertical showers and just gets significant ~ 80 deg.

**Review by cg-laser — APPROVED** [review]

**Pull request merged**
