### PR TITLE
Changes relative import to absolute import

### PR DESCRIPTION
**Pull request by christophwelling**
Python3 no longer supports implicit relative imports, so these imports were changed to absolute imports

### CODE REVIEW

**Comment by fschlueter** [comment]
Why not importing from radiotools import stats at the top of the file?

**Comment by christophwelling** [comment]
Well, I don't know why whoever wrote this decided to do the imports here, I just kept it.
I decided to not use the from ... import ..., because there is also a function that has "stats" as a parameter and this way makes it a little less confusing

**Comment by anelles** [comment]
We can move the import to the top. I think @cg-laser has the habit of doing this in the middle of the code to stay efficient and import only if needed, but then never gets to cleaning up after, when it is imported at several places.

**Comment by cg-laser** [comment]
thats fine. It was originally at the bottom because it was an external package, and I didn't want to introduce the dependency to everything. Now that it is integrated into radiotools, we should import it at the top. Thanks for fixing.

**Review by cg-laser — APPROVED** [review]

**Pull request merged**
